# Generated by Django 3.2.18 on 2023-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230425_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Добавить слаг не блее 256 символов. Слаг должен быть уникальным для каждой категории.', max_length=256, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Добавить название категории не блее 256 символов.', max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Добавить слаг не более 256 символов. Слаг должен быть уникальным для каждого товара.', max_length=256, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Добавить название товара не более 256 символов.', max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
